language: python
python:
- '3.4'
cache:
  directories:
    - $HOME/.cache/pip
env:
- DJANGO=Django>=1.9
sudo: false
install:
- pip install coveralls -r requirements.txt --use-mirrors
before_script:
- psql template1 -c 'create extension hstore;'
- psql template1 -c 'create extension postgis;'
script: py.test
addons:
  postgresql: '9.4'
services:
  - elasticsearch
notifications:
  slack:
    secure: Hxh7X9ckorBlD2MRiSh/TE6nC0kyEZrEmegx3FHQgwOm5tNCZcJUoJprmEXA82SMxlbl12XcNLhFZaeQd6Gt2AF5AvTjbJLsLZBRebbKA6We1dCSpyHSGXy+GGWRD0J1OYstk2jg5fWmsscusLZ0MFbybg8qwmsv7/LOG+QoX6M=
after_success: coveralls
